### ISSUE TITLE
Downstreaming doesn't work in a bare checkout

### ISSUE THREAD

**Issue by jgraham** [mjzffr/version-control-tools#1]
The `git_gecko` and `git_wpt`objects are set up to point at bare checkouts, with the assumption that we would use semi-persistent worktrees for all actual git operations. The downstreaming code assumes that it can do working tree operations on the paths passed in which at the moment are the bare repos. We should probably change this to create a worktree for each PR we downstream, since this will also provide a convenient place to store logfiles from try &c.

**Comment by mjzffr** [comment]
Done in 01b7c868
