### ISSUE TITLE
Generated try syntax may be very long

### ISSUE THREAD

**Issue by mjzffr** [mjzffr/version-control-tools#13]
For the narrow try push, we generate try syntax (--try-test-paths) based on `wpt tests-affected`. This may result in a very long try string and hit some message limit on the try server. We could group common path prefixes to shorten this.

**Comment by jgraham** [comment]
Will https://github.com/mjzffr/version-control-tools/issues/18 solve this, or will we still need to do this in that case?

**Comment by mjzffr** [comment]
#18 would solve it.
