### ISSUE TITLE
Handle successful try push

### ISSUE THREAD

**Issue by mjzffr** [mjzffr/version-control-tools#15]
- [x] Determine the task group id that corresponds to each try push we make

When we see a task-group-resolved message for a task group id that corresponds to a try push we've made. 

- [x] Fetch relevant jobs logs from TaskCluster.
- [x] Determine what kind of try push it was ("narrow", "stability"), which PR it was for, etc.
        - Decide what the next step is: e.g. create a "stability" try push
- [ ] Determine the overall result of the try push: "infrastructure busted", "too many tests failed", "green enough", "cancelled"
           - Decide whether to flag for manual intervention, retry, update expectation metadata or ignore.
- [x] Update metadata (with ./mach wpt-update)
- [x] Comment on the corresponding bug
- [ ] Update PR status.

**Comment by jgraham** [comment]
I believe this is now working well enough to get us started? Any remaining items should be new issues.
