### ISSUE TITLE
Configure wpt repo to trigger taskcluster task per PR and report on treeherder

### ISSUE THREAD

**Issue by mjzffr** [mjzffr/version-control-tools#26]
This is an idea from @whimboo as an alternative to having try-push logic the downstreaming code. 

In theory, we could add a taskcluster.yml to the wpt repo to specify some TaskCluster task to run per PR, for example. And we can tell Treeherder to pay attention to the results. The task can take care of merging the PR changes into a clone of m-c and figure out what tests to run. 

This would simplify how we detect completed test jobs (since we wouldn't have to listen for all tasks on try) and how we recover from interruption or data loss. (Easier to reconstruct which test runs correspond to which sync.)

**Comment by whimboo** [comment]
The project taskcluster-github can be found at https://github.com/taskcluster/taskcluster-github.

**Comment by jgraham** [comment]
We currently don't make all platforms available to GitHub builds (so far just Linux and Windows in an unsupported fashion), so this wouldn't work (I'd already like to use TaskCluster as an alternative to Travis for other reasons).

I did wonder, however, if we could make a taskcluster job that depends on all the wpt jobs and updates the metadata (it could upload a diff or something). Then we would still have to manually schedule the initial job, but we wouldn't have to manually trigger the update, just download the metadata patch when that job's done.
