### ISSUE TITLE
Allow the possibility of running try on different platforms at different times

### ISSUE THREAD

**Issue by jgraham** [mjzffr/version-control-tools#6]
In particular we might want to run a linux+windows run and only an OSX run if we see platform differences in the expectation data, or something. That will mean that we are wrong sometimes and have to push fixup commits, but it will also mean that we don't end up in long queues for OSX jobs.

**Comment by mjzffr** [comment]
Also restrict which platforms we run on depending on what tests are affected, at least for now. For example, if only wdspec tests are affected then only schedule linux64 debug.
